global_costmap:

  footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
  #robot_radius: 0.17

  cost_scaling_factor: 2.0
  map_type: costmap

  global_frame: map
  robot_base_frame: base_link

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.5

  always_send_full_costmap: true
  static_map: true
  plugins: 
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    obstacle_range: 40
    raytrace_range: 40
    track_unknown_space: true
    observation_sources: livox
    livox: {sensor_frame: livox, data_type: PointCloud2, topic: /livox/lidar_pointcloud2, marking: true, clearing: true, min_obstacle_height: 0.2, max_obstacle_height: 1}
  inflation_layer:
    inflation_radius: 4.0
    
 